/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.42
 * Generated at: 2026-08-24 14:17:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class modifier_002dmesure_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1787487073554L));
    _jspx_dependants.put("jar:file:/C:/Users/HP/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602873972000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Modifier la mesure - Suivi Glycémie</title>\r\n");
      out.write("    <!-- Bootstrap 5 -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-light d-flex align-items-center justify-content-center py-5\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card shadow-sm p-4\" style=\"width: 100%; max-width: 500px; border-radius: 15px;\">\r\n");
      out.write("        <div class=\"text-center mb-4\">\r\n");
      out.write("            <h3 class=\"fw-bold text-warning\">✏️ Modifier la mesure</h3>\r\n");
      out.write("            <p class=\"text-muted small\">Mettez à jour l'ensemble de vos données de glycémie</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
 if(request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("            <div class=\"alert alert-danger py-2 small text-center\" role=\"alert\">\r\n");
      out.write("                ");
      out.print( request.getAttribute("error") );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mesure/modifier\" method=\"post\">\r\n");
      out.write("            <!-- ID caché indispensable -->\r\n");
      out.write("            <input type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${glycemie.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("            <!-- 1. Valeur de la glycémie -->\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label class=\"form-label fw-semibold\">Valeur (g/L ou mg/dL)</label>\r\n");
      out.write("                <input type=\"text\" name=\"valeur\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${glycemie.valeur}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required placeholder=\"ex: 1.25\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 2. Type de mesure -->\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label class=\"form-label fw-semibold\">Type de mesure</label>\r\n");
      out.write("                <select name=\"typeMesure\" id=\"typeMesure\" class=\"form-select\" required onchange=\"gererChampsInsuline()\">\r\n");
      out.write("                    <option value=\"À jeun\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${glycemie.type == 'À jeun' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">À jeun</option>\r\n");
      out.write("                    <option value=\"Avant repas\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${glycemie.type == 'Avant repas' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Avant repas</option>\r\n");
      out.write("                    <option value=\"Après repas\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${glycemie.type == 'Après repas' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Après repas</option>\r\n");
      out.write("                    <option value=\"Après déjeuner\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${glycemie.type == 'Après déjeuner' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Après déjeuner</option>\r\n");
      out.write("                    <option value=\"Avant diner\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${glycemie.type == 'Avant diner' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Avant diner</option>\r\n");
      out.write("                    <option value=\"Après diner\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${glycemie.type == 'Après diner' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Après diner</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 3. Insuline 1 (Nom et Unités) -->\r\n");
      out.write("            <div class=\"card p-3 mb-3 bg-light border-0\" id=\"blocInsuline1\">\r\n");
      out.write("                <label class=\"form-label fw-semibold text-primary\" id=\"labelInsuline1\">Première Insuline</label>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-7\">\r\n");
      out.write("                        <input type=\"text\" name=\"nomInsuline1\" id=\"nomInsuline1\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty glycemie.insulines[0] ? glycemie.insulines[0].type : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Type (ex: Lente)\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-5\">\r\n");
      out.write("                        <input type=\"number\" step=\"0.5\" name=\"uniteInsuline1\" id=\"uniteInsuline1\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty glycemie.insulines[0] ? glycemie.insulines[0].unite : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Unités\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 4. Insuline 2 (Nom et Unités) -->\r\n");
      out.write("            <div class=\"card p-3 mb-4 bg-light border-0\" id=\"blocInsuline2\">\r\n");
      out.write("                <label class=\"form-label fw-semibold text-primary\">Deuxième Insuline (optionnel)</label>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-7\">\r\n");
      out.write("                        <input type=\"text\" name=\"nomInsuline2\" id=\"nomInsuline2\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty glycemie.insulines[1] ? glycemie.insulines[1].type : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Type (ex: Rapide)\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-5\">\r\n");
      out.write("                        <input type=\"number\" step=\"0.5\" name=\"uniteInsuline2\" id=\"uniteInsuline2\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty glycemie.insulines[1] ? glycemie.insulines[1].unite : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Unités\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard\" class=\"btn btn-outline-secondary w-48\">Annuler</a>\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-warning fw-bold w-48 text-white\">Enregistrer</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Script de gestion dynamique strict -->\r\n");
      out.write("    <script>\r\n");
      out.write("        function gererChampsInsuline() {\r\n");
      out.write("            const typeSelect = document.getElementById('typeMesure');\r\n");
      out.write("            const val = typeSelect.value.toLowerCase();\r\n");
      out.write("\r\n");
      out.write("            const blocInsuline1 = document.getElementById('blocInsuline1');\r\n");
      out.write("            const blocInsuline2 = document.getElementById('blocInsuline2');\r\n");
      out.write("            const nomInsuline1 = document.getElementById('nomInsuline1');\r\n");
      out.write("            const uniteInsuline1 = document.getElementById('uniteInsuline1');\r\n");
      out.write("            const nomInsuline2 = document.getElementById('nomInsuline2');\r\n");
      out.write("            const uniteInsuline2 = document.getElementById('uniteInsuline2');\r\n");
      out.write("            const labelInsuline1 = document.getElementById('labelInsuline1');\r\n");
      out.write("\r\n");
      out.write("            // Si le type contient \"après\" ou \"apres\" -> TOUT MASQUER ET VIDER STRICTEMENT\r\n");
      out.write("            if (val.includes('après') || val.includes('apres')) {\r\n");
      out.write("                blocInsuline1.style.display = 'none';\r\n");
      out.write("                blocInsuline2.style.display = 'none';\r\n");
      out.write("\r\n");
      out.write("                nomInsuline1.removeAttribute('required');\r\n");
      out.write("                uniteInsuline1.removeAttribute('required');\r\n");
      out.write("\r\n");
      out.write("                nomInsuline1.value = '';\r\n");
      out.write("                uniteInsuline1.value = '';\r\n");
      out.write("                nomInsuline2.value = '';\r\n");
      out.write("                uniteInsuline2.value = '';\r\n");
      out.write("            }\r\n");
      out.write("            // Sinon (À jeun, Avant repas, Avant diner) -> AFFICHER ET RENDRE OBLIGATOIRE\r\n");
      out.write("            else {\r\n");
      out.write("                blocInsuline1.style.display = '';\r\n");
      out.write("                blocInsuline2.style.display = '';\r\n");
      out.write("\r\n");
      out.write("                nomInsuline1.setAttribute('required', 'required');\r\n");
      out.write("                uniteInsuline1.setAttribute('required', 'required');\r\n");
      out.write("                labelInsuline1.innerHTML = 'Première Insuline <span class=\"text-danger\">*</span>';\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', gererChampsInsuline);\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
